# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='city',
        ),
    ]
