# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_movie_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='is_running',
        ),
        migrations.AddField(
            model_name='runningmovie',
            name='theatre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.Theatre'),
            preserve_default=False,
        ),
    ]
